# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-08 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181104_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='parent',
        ),
        migrations.AddField(
            model_name='learner',
            name='parents',
            field=models.ManyToManyField(to='users.Parent'),
        ),
    ]
