# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-09 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181108_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='parents',
        ),
    ]
