# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbn',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
