# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='isbn',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to='books.Author'),
        ),
    ]
