# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookItem',
        ),
    ]
