# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 11:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=100)),
                ('submission_date', models.DateField()),
                ('is_complete', models.BooleanField(default=True)),
                ('date_marked_as_complete', models.DateField()),
                ('image', models.ImageField(upload_to=b'')),
                ('observation', models.TextField()),
                ('submitter', models.CharField(choices=[('parent', 'parent'), ('faculty', 'faculty'), ('expert', 'expert'), ('child', 'child')], max_length=10)),
                ('start_time', models.DateField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
