# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obspost', '0003_auto_20160825_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='childsheet',
            name='foldercode',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
    ]
