# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-17 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obspost', '0004_childsheet_foldercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='observation',
            name='submitter',
            field=models.CharField(blank=True, choices=[('parent', 'parent'), ('faculty', 'faculty'), ('expert', 'expert'), ('child', 'child')], max_length=10, null=True),
        ),
    ]
