# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-18 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obspost', '0005_auto_20170717_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
