# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-04 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181104_1043'),
        ('obspost', '0006_auto_20170718_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservedChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Learner')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obspost.Observation')),
            ],
        ),
    ]
