# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-08 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obspost', '0007_observedchild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observedchild',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obspost.Observation'),
        ),
    ]
